# Copyright (c) Indrajit Roy
#
# This file is licensed under the Affero General Public License version 3 or
# any later version.
#
# See the file LICENSE for details.

[alias]
coverage = ["llvm-cov", "--html"]
demo = ["run", "--example", "rusotp"]

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[target.x86_64-apple-darwin]
linker = "rust-lld"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"