# Copyright (c) Indrajit Roy
#
# This file is licensed under the Affero General Public License version 3 or
# any later version.
#
# See the file LICENSE for details.

[alias]
coverage = ["llvm-cov", "--html"]
demo = ["run", "--example", "rusotp"]